name: mask_net
description: "An anonymous Social Networking platform for Professionals"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^7.8.4
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  pinput: ^3.0.1
  flutter_svg: ^2.0.9
  permission_handler: ^11.0.1
  logger: ^2.0.2+1
  dio: ^5.4.0
  url_launcher: ^6.2.4
  easy_rich_text: ^2.1.0
  shimmer: ^3.0.0
  file_picker: ^6.1.1
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  firebase_messaging: ^14.7.10
  firebase_core: ^2.24.2
  flutter_local_notifications: ^16.3.2
  flutter_launcher_icons: ^0.13.1
  fluttertoast: ^8.2.5
  firebase_analytics: ^10.10.7
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  image_picker: ^1.1.2
  timeago: ^3.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  
flutter:

  uses-material-design: true

  assets:
    - assets/icon/
    
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
